use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'FMDB-isExecutingStatement_Example' do
  pod 'FMDB-isExecutingStatement', :path => '../'

  target 'FMDB-isExecutingStatement_Tests' do
    inherit! :search_paths

    
  end
end
